### ISSUE TITLE
Definir todas las tareas iniciales sobre el backend

### ISSUE THREAD

**Issue by Teett** [Teett/ds4a-team-62#18]

**Comment by jsbarriosmunal** [comment]
@cronfer1 ¿podemos cerrar este issue?

**Comment by jsbarriosmunal** [comment]
Back-end
The back-end was created with the purpose of having access to the database in a secure way, for this an application was created in flask, which accesses the database through sql queries, and orders the data in a json so that the front-end can read them through API requests, this is possible through CORS

RDS
For the RDS, a database was created in which all the records that the user wants to enter are saved, this to have consistency in the data, and to be able to read them constantly.

Elastickbeanstalk
It is the AWS service that allows the deployment of the application in a simple way, in which both the backend and the frontend are deployed and communicate through http requests, this service is chosen due to its ease of implementation and the advantages it has , where it is in charge of executing processes such as cloudwatch where the application logs are seen, it also deploys services such as the load balancer and the auto scaling Group, thus allowing connection from any device with internet access.
